export const data = [
  {
    id: "1",
    date: "2023-12-12",
    description: "설명 1",
    image: require("../assets/bear.jpg"),
  },
  {
    id: "2",
    date: "2023-12-13",
    description: "설명 2",
    image: require("../assets/bear.jpg"),
  },
  {
    id: "3",
    date: "2023-12-13",
    description: "설명 3",
    image: require("../assets/bear.jpg"),
  },
  {
    id: "4",
    date: "2023-12-14",
    description: "설명 4",
    image: require("../assets/bear.jpg"),
  },
  {
    id: "5",
    date: "2023-12-15",
    description: "설명 5",
    image: require("../assets/bear.jpg"),
  },
  {
    id: "6",
    date: "2023-12-16",
    description: "설명 6",
    image: require("../assets/bear.jpg"),
  },
  {
    id: "7",
    date: "2023-12-17",
    description: "설명 7",
    image: require("../assets/bear.jpg"),
  },
  {
    id: "8",
    date: "2023-12-18",
    description: "설명 8",
    image: require("../assets/bear.jpg"),
  },
  {
    id: "9",
    date: "2023-12-19",
    description: "설명 9",
    image: require("../assets/bear.jpg"),
  },
  {
    id: "10",
    date: "2023-12-20",
    description: "설명 10",
    image: require("../assets/bear.jpg"),
  },
  {
    id: "11",
    date: "2023-12-19",
    description: "설명 11",
    image: require("../assets/bear.jpg"),
  },
  {
    id: "12",
    date: "2023-12-20",
    description: "설명 12",
    image: require("../assets/bear.jpg"),
  },
  {
    id: "1",
    date: "2023-12-12",
    description: "설명 1",
    image: require("../assets/bear.jpg"),
  },
  {
    id: "2",
    date: "2023-12-13",
    description: "설명 2",
    image: require("../assets/bear.jpg"),
  },
  {
    id: "3",
    date: "2023-12-13",
    description: "설명 3",
    image: require("../assets/bear.jpg"),
  },
  {
    id: "4",
    date: "2023-12-14",
    description: "설명 4",
    image: require("../assets/bear.jpg"),
  },
  {
    id: "5",
    date: "2023-12-15",
    description: "설명 5",
    image: require("../assets/bear.jpg"),
  },
  {
    id: "6",
    date: "2023-12-16",
    description: "설명 6",
    image: require("../assets/bear.jpg"),
  },
  {
    id: "7",
    date: "2023-12-17",
    description: "설명 7",
    image: require("../assets/bear.jpg"),
  },
  {
    id: "8",
    date: "2023-12-18",
    description: "설명 8",
    image: require("../assets/bear.jpg"),
  },
  {
    id: "9",
    date: "2023-12-19",
    description: "설명 9",
    image: require("../assets/bear.jpg"),
  },
  {
    id: "10",
    date: "2023-12-20",
    description: "설명 10",
    image: require("../assets/bear.jpg"),
  },
  {
    id: "11",
    date: "2023-12-19",
    description: "설명 11",
    image: require("../assets/bear.jpg"),
  },
  {
    id: "12",
    date: "2023-12-20",
    description: "설명 12",
    image: require("../assets/bear.jpg"),
  },
  {
    id: "1",
    date: "2023-12-12",
    description: "설명 1",
    image: require("../assets/bear.jpg"),
  },
  {
    id: "2",
    date: "2023-12-13",
    description: "설명 2",
    image: require("../assets/bear.jpg"),
  },
  {
    id: "3",
    date: "2023-12-13",
    description: "설명 3",
    image: require("../assets/bear.jpg"),
  },
  {
    id: "4",
    date: "2023-12-14",
    description: "설명 4",
    image: require("../assets/bear.jpg"),
  },
  {
    id: "5",
    date: "2023-12-15",
    description: "설명 5",
    image: require("../assets/bear.jpg"),
  },
  {
    id: "6",
    date: "2023-12-16",
    description: "설명 6",
    image: require("../assets/bear.jpg"),
  },
  {
    id: "7",
    date: "2023-12-17",
    description: "설명 7",
    image: require("../assets/bear.jpg"),
  },
  {
    id: "8",
    date: "2023-12-18",
    description: "설명 8",
    image: require("../assets/bear.jpg"),
  },
  {
    id: "9",
    date: "2023-12-19",
    description: "설명 9",
    image: require("../assets/bear.jpg"),
  },
  {
    id: "10",
    date: "2023-12-20",
    description: "설명 10",
    image: require("../assets/bear.jpg"),
  },
  {
    id: "11",
    date: "2023-12-19",
    description: "설명 11",
    image: require("../assets/bear.jpg"),
  },
  {
    id: "12",
    date: "2023-12-20",
    description: "설명 12",
    image: require("../assets/bear.jpg"),
  },
  {
    id: "1",
    date: "2023-12-12",
    description: "설명 1",
    image: require("../assets/bear.jpg"),
  },
  {
    id: "2",
    date: "2023-12-13",
    description: "설명 2",
    image: require("../assets/bear.jpg"),
  },
  {
    id: "3",
    date: "2023-12-13",
    description: "설명 3",
    image: require("../assets/bear.jpg"),
  },
  {
    id: "4",
    date: "2023-12-14",
    description: "설명 4",
    image: require("../assets/bear.jpg"),
  },
  {
    id: "5",
    date: "2023-12-15",
    description: "설명 5",
    image: require("../assets/bear.jpg"),
  },
  {
    id: "6",
    date: "2023-12-16",
    description: "설명 6",
    image: require("../assets/bear.jpg"),
  },
  {
    id: "7",
    date: "2023-12-17",
    description: "설명 7",
    image: require("../assets/bear.jpg"),
  },
  {
    id: "8",
    date: "2023-12-18",
    description: "설명 8",
    image: require("../assets/bear.jpg"),
  },
  {
    id: "9",
    date: "2023-12-19",
    description: "설명 9",
    image: require("../assets/bear.jpg"),
  },
  {
    id: "10",
    date: "2023-12-20",
    description: "설명 10",
    image: require("../assets/bear.jpg"),
  },
  {
    id: "11",
    date: "2023-12-19",
    description: "설명 11",
    image: require("../assets/bear.jpg"),
  },
  {
    id: "12",
    date: "2023-12-20",
    description: "설명 12",
    image: require("../assets/bear.jpg"),
  },
  {
    id: "1",
    date: "2023-12-12",
    description: "설명 1",
    image: require("../assets/bear.jpg"),
  },
  {
    id: "2",
    date: "2023-12-13",
    description: "설명 2",
    image: require("../assets/bear.jpg"),
  },
  {
    id: "3",
    date: "2023-12-13",
    description: "설명 3",
    image: require("../assets/bear.jpg"),
  },
  {
    id: "4",
    date: "2023-12-14",
    description: "설명 4",
    image: require("../assets/bear.jpg"),
  },
  {
    id: "5",
    date: "2023-12-15",
    description: "설명 5",
    image: require("../assets/bear.jpg"),
  },
  {
    id: "6",
    date: "2023-12-16",
    description: "설명 6",
    image: require("../assets/bear.jpg"),
  },
  {
    id: "7",
    date: "2023-12-17",
    description: "설명 7",
    image: require("../assets/bear.jpg"),
  },
  {
    id: "8",
    date: "2023-12-18",
    description: "설명 8",
    image: require("../assets/bear.jpg"),
  },
  {
    id: "9",
    date: "2023-12-19",
    description: "설명 9",
    image: require("../assets/bear.jpg"),
  },
  {
    id: "10",
    date: "2023-12-20",
    description: "설명 10",
    image: require("../assets/bear.jpg"),
  },
  {
    id: "11",
    date: "2023-12-19",
    description: "설명 11",
    image: require("../assets/bear.jpg"),
  },
  {
    id: "12",
    date: "2023-12-20",
    description: "설명 12",
    image: require("../assets/bear.jpg"),
  },
];
